### ISSUE TITLE
is it working, yet?

### ISSUE THREAD

**Issue by Sebara0** [visuxls/tipranks#1]
Hi, 
I have an issue when the program tries to connect
File "D:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button class="client-templates-loginPage-styles__submitButton">...</button> is not clickable at point (571, 558). Other element would receive the click: <div>...</div>
  (Session info: headless chrome=105.0.5195.125)

My user is "basic". Should I have another user type?

Thanks in advance

**Comment by visuxls** [comment]
Hi. I just pushed a new release and seems to have fixed the issue. Let me know if it's fixed for you. 

I developed the package with an Ultimate and Premium account so most methods will require a paid account.

**Comment by visuxls** [comment]
Hey, I just pushed a new release and Selenium is no longer required. Login is now request based.
