### ISSUE TITLE
WebDriverException: Message: 'chromedriver' executable needs to be in PATH

### ISSUE THREAD

**Issue by lujangus** [visuxls/tipranks#2]
Hi,

I'm getting the following error: 

File ~\miniconda3\lib\site-packages\selenium\webdriver\common\service.py:81, in Service.start(self)
     79 except OSError as err:
     80     if err.errno == errno.ENOENT:
---> 81         raise WebDriverException(
     82             "'{}' executable needs to be in PATH. {}".format(
     83                 os.path.basename(self.path), self.start_error_message)
     84         )
     85     elif err.errno == errno.EACCES:
     86         raise WebDriverException(
     87             "'{}' executable may have wrong permissions. {}".format(
     88                 os.path.basename(self.path), self.start_error_message)
     89         )

WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home

Any thoughts on how to solve it?

**Comment by visuxls** [comment]
Hey, this error is usually because the chromedriver.exe isn't in your project's folder.

Although, I just reworked login logic and Selenium is no longer required. You won't have this issue on the new release.
